spring.application.name=vehicleBooking

spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_booking
spring.datasource.username=postgres
spring.datasource.password=pr00vit00

spring.flyway.schemas=vehicle_booking
spring.flyway.create-schemas=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=vehicle_booking